apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: ClusterIP
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 19093
      targetPort: 19093