apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service-container
          image: leewon2/restaurant-service:latest
          ports:
            - containerPort: 19093
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb:3306/hangry-database"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
