apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server-container
          image: leewon2/eureka-server:latest
          ports:
            - containerPort: 19090
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eureka-server"
