apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container
          image: leewon2/auth-service:latest
          ports:
            - containerPort: 19098
          env:
            - name: JWT_SECRET_KEY
              value: "piGhz+G1SCtvDWv/sVXxOd4iSnhCyo6S0GkzwuF9wbs="
            - name: JWT_ACCESS_EXPIRATION
              value: "3600000"
            - name: JWT_REFRESH_EXPIRATION
              value: "604800000"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "systempass"
