apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service-container
          image: leewon2/reservation-service:latest
          ports:
            - containerPort: 19094
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb:3306/hangry-database?allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_USERNAME
              value: "default"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "systempass"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

            - name: GATEWAY_URL
              value: "http://gateway-service:19091"
