apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  type: ClusterIP
  selector:
    app: reservation-service
  ports:
    - protocol: TCP
      port: 19094
      targetPort: 19094






