@baseUrl = http://localhost:19091
@access_token = variable value

### 회원가입
POST {{baseUrl}}/api/users/signup
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1",
  "name": "user1",
  "phone": "010-1234-1234",
  "role" : "ADMIN",
  "slackId": "user1@gmail.com"
}

### 로그인
POST {{baseUrl}}/api/auth/signin
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1"
}
> {%
    client.global.set("access_token", response.body.accessToken)
%}

### New Access Token
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDIiLCJyb2xlIjoiUkVGUkVTSCIsImlhdCI6MTc0NDMzNjc0NywiZXhwIjoxNzQ0OTQxNTQ3fQ.MZfcVYl-gWvFutX0cenNEIMXENiqKvIOEVRDjI8ElrU"
}

### 로그아웃
POST {{baseUrl}}/api/auth/logout
Content-Type: application/json
Authorization: {{access_token}}
