global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:19095']

  - job_name: 'benefit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
     - targets: [ 'host.docker.internal:19096' ]