apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  labels:
    app: review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service-container
          image: leewon2/review-service:latest
          ports:
            - containerPort: 19095
          env:
            - name: SPRING_APPLICATION_NAME
              value: "review-service"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb:3306/hangry-database"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "systempass"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
